# Generated by Django 4.1.7 on 2023-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                (
                    "resume_url",
                    models.URLField(
                        help_text="Ссылка на резюме автора", verbose_name="Резюме"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        help_text="Ссылка на гитхаб автора", verbose_name="GitHub"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Почта автора", max_length=254, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные об авторе",
                "verbose_name_plural": "Данные об авторе",
            },
        ),
    ]
