# Generated by Django 4.1.13 on 2024-03-16 11:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="full_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Подробное описание",
                help_text="Подробное описание выполненной работы",
                verbose_name="Подробное описание работы",
            ),
        ),
    ]
